name = "SpelledOut"
uuid = "4728c690-e668-4265-bc0d-51a8c0f93067"
authors = ["Jake W. Ireland <jakewilliami@icloud.com> and contributors"]
version = "1.0.1"

[deps]
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"

[compat]
DecFP = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
